/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Administrador.Vista;

import Administrador.Servicios.PersonaServicesInt;
import Modelo.EnumTipoComida;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Victor
 */
public class vtnAgregarComida extends javax.swing.JInternalFrame {
    private PersonaServicesInt personaServices;
    /** Creates new form vtnAgregarComida */
    public vtnAgregarComida(PersonaServicesInt personaServices) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAgregarComida = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipoComida = new javax.swing.JComboBox<>();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabelFoto = new javax.swing.JLabel();
        jLabelCamposRequeridos = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelArchivoSeleccionado = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Comida");

        jLabelAgregarComida.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabelAgregarComida.setForeground(new java.awt.Color(26, 85, 118));
        jLabelAgregarComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarComida.setText("Agregar Comida");

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(26, 85, 118));
        jLabelCodigo.setText("*Código");

        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(26, 85, 118));
        jLabelName.setText("*Nombre");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(26, 85, 118));
        jLabelTipo.setText("*Tipo");

        jComboBoxTipoComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especial", "Comida Rápida", "Postre", "Bebida" }));
        jComboBoxTipoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoComidaActionPerformed(evt);
            }
        });

        jLabelValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(26, 85, 118));
        jLabelValor.setText("*Valor");

        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });

        jLabelFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFoto.setForeground(new java.awt.Color(26, 85, 118));
        jLabelFoto.setText("*Fotografia");

        jLabelCamposRequeridos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCamposRequeridos.setForeground(new java.awt.Color(26, 85, 118));
        jLabelCamposRequeridos.setText("*Campos requeridos");

        jButtonCancelar.setBackground(new java.awt.Color(242, 153, 74));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAgregar.setBackground(new java.awt.Color(242, 153, 74));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButton1.setText("Seleccionar Archivos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelArchivoSeleccionado.setText("No hay archivos seleccionados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAgregarComida, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCamposRequeridos)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                            .addComponent(jButtonAgregar))
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelValor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTipo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldCode, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxTipoComida, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelArchivoSeleccionado, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabelAgregarComida)
                .addGap(18, 18, 18)
                .addComponent(jLabelCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelArchivoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabelCamposRequeridos)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAgregar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    private void jComboBoxTipoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoComidaActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int  returnValue = jfc.showOpenDialog(null);
        
        if (returnValue==JFileChooser.APPROVE_OPTION){
            File selectedFile = jfc.getSelectedFile();
            this.jLabelArchivoSeleccionado.setText(selectedFile.getAbsolutePath());
            System.out.println(selectedFile.getAbsolutePath());
            
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
                 
            String Foto,  Codigo,  Nombre, Tipo;
            float Valor;
            
            
            Foto=jLabelArchivoSeleccionado.getText();
            Codigo=jTextFieldCode.getText();
     
            Nombre=jTextFieldNombre.getText();
            Tipo=(String) jComboBoxTipoComida.getSelectedItem();
            Valor= Float.parseFloat(this.jTextFieldPrice.getText());
            int codigoResultado=this.personaServices.registrarComida(Foto, Codigo, Nombre, Tipo, Valor);
            
            if(codigoResultado==1)
            {
                Utilidades.Utilidades.mensajeExito("Registro exitoso", "registro exitoso");
            }
            else if(codigoResultado==0)
            {
                Utilidades.Utilidades.mensajeAdvertencia("Error de conexión", "error en el registro");         
            }
            else
            {
                Utilidades.Utilidades.mensajeAdvertencia("la persona ya se encuentra registra en el sistema", "error en el registro");
            } 
    }//GEN-LAST:event_jButtonAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxTipoComida;
    private javax.swing.JLabel jLabelAgregarComida;
    private javax.swing.JLabel jLabelArchivoSeleccionado;
    private javax.swing.JLabel jLabelCamposRequeridos;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables

}
